name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Compilar calculadora
        run: gcc "calculadora.c" -o calculadora

      - name: Executar programa
        run: echo "1 10 5" | ./calculadora
